<?php

namespace Nixilla\JobeetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobeetAffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobeetAffiliateRepository extends EntityRepository
{
}