Nixilla\JobeetBundle\Entity\JobeetAffiliate:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    url:
      type: string
      length: 255
    email:
      type: string
      length: 255
    token:
      type: string
      length: 255
    is_active:
      type: boolean
  lifecycleCallbacks: {  }
  manyToMany:
    categories:
      targetEntity: JobeetCategory
      joinTable:
        name: JobeetCategoryAffiliate
        joinColumns:
          category_id:
            referencedColumnName: id
        inverseJoinColumns:
          affiliate_id:
            referencedColumnName: id

